name: Rust

on:
  push:
    branches: [ canon ]
  pull_request:
    branches: [ canon ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: cargo build --verbose --workspace
    - name: Run tests
      run: cargo test --verbose --workspace
