name: 'Publish canon demo'

on:
  workflow_dispatch:
  push:
    branches: [canon]

env:
  CARGO_TERM_COLOR: always

permissions:
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install wasm-pack
      run: cargo install wasm-pack
    - name: Run wasm-pack
      run: |
        cd auto-knuffel-demo
        wasm-pack build --target web
        mkdir dist
        cp index.html dist
        mkdir dist/pkg
        cp pkg/*.js pkg/*.wasm dist/pkg
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/canon' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./auto-knuffel-demo/dist
        force_orphan: true
